name: Daily
on:
  workflow_dispatch:

jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
      
      - name: My GitHub Status
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-
  
      - name: Run
        run: |
          source venv/bin/activate
          python main.py
      
